language: c

addons:
  ssh_known_hosts: 
  - git.oschina.net
  - 120.55.226.24

before_install:
- openssl aes-256-cbc -K $encrypted_942a9424c0f4_key -iv $encrypted_942a9424c0f4_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa

script:
- export WORK=$HOME/.sync
- travis_wait 30 ./sync-with-ssh-agent.sh

cache:
  directories:
  - $HOME/.sync
