language: c
env:
  matrix:
  - PRJ=riscv-test-env       SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-tests          SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-pk             SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-opcodes        SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-llvm           SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-clang          SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-isa-sim        SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-newlib         SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-dejagnu        SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-glibc          SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-gcc            SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-binutils-gdb   SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-gnu-toolchain  SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-fesvr          SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-tools          SRC=https://github.com/riscv   DST=https://git.oschina.net/cnrv
  - PRJ=riscv-torture        SRC=https://github.com/ucb-bar DST=https://git.oschina.net/cnrv
  - PRJ=berkeley-hardfloat   SRC=https://github.com/ucb-bar DST=https://git.oschina.net/cnrv
  - PRJ=firrtl               SRC=https://github.com/ucb-bar DST=https://git.oschina.net/cnrv
  - PRJ=chisel3              SRC=https://github.com/ucb-bar DST=https://git.oschina.net/cnrv
  - PRJ=rocket-chip          SRC=https://github.com/ucb-bar DST=https://git.oschina.net/cnrv
before_install:
- openssl aes-256-cbc -K $encrypted_942a9424c0f4_key -iv $encrypted_942a9424c0f4_iv
  -in setup-credential.sh.enc -out setup-credential.sh -d
- chmod +x setup-credential.sh
- "./setup-credential.sh"
script:
- export WORK=$HOME/.sync
- "./sync.sh"
cache:
  directories:
  - "$HOME/.sync"
