language: python
env:
  matrix:
  - PRJ=chisel-testers                                 SRC=https://github.com/freechipsproject
  - PRJ=chisel3                                        SRC=https://github.com/freechipsproject
  - PRJ=firrtl                                         SRC=https://github.com/freechipsproject
  - PRJ=firrtl-interpreter                             SRC=https://github.com/freechipsproject
  - PRJ=rocket-chip                                    SRC=https://github.com/freechipsproject
  - PRJ=debug-taskgroup                                SRC=https://github.com/riscv
  - PRJ=homebrew-riscv                                 SRC=https://github.com/riscv
  - PRJ=riscv-4th-workshop-tutorials                   SRC=https://github.com/riscv
  - PRJ=riscv-angel                                    SRC=https://github.com/riscv
  - PRJ=riscv-asm-manual                               SRC=https://github.com/riscv
  - PRJ=riscv-binutils-gdb                             SRC=https://github.com/riscv
  - PRJ=riscv-buildbot-infra                           SRC=https://github.com/riscv
  - PRJ=riscv-clang                                    SRC=https://github.com/riscv
  - PRJ=riscv-debug-spec                               SRC=https://github.com/riscv
  - PRJ=riscv-dejagnu                                  SRC=https://github.com/riscv
  - PRJ=riscv-elf-psabi-doc                            SRC=https://github.com/riscv
  - PRJ=riscv-fesvr                                    SRC=https://github.com/riscv
  - PRJ=riscv-gcc                                      SRC=https://github.com/riscv
  - PRJ=riscv-glibc                                    SRC=https://github.com/riscv
  - PRJ=riscv-gnu-toolchain                            SRC=https://github.com/riscv
  - PRJ=riscv-go                                       SRC=https://github.com/riscv
  - PRJ=riscv-isa-manual                               SRC=https://github.com/riscv
  - PRJ=riscv-isa-sim                                  SRC=https://github.com/riscv
  - PRJ=riscv-libffi                                   SRC=https://github.com/riscv
  - PRJ=riscv-linux                                    SRC=https://github.com/riscv
  - PRJ=riscv-llvm                                     SRC=https://github.com/riscv
  - PRJ=riscv-newlib                                   SRC=https://github.com/riscv
  - PRJ=riscv-old-gcc                                  SRC=https://github.com/riscv
  - PRJ=riscv-opcodes                                  SRC=https://github.com/riscv
  - PRJ=riscv-openocd                                  SRC=https://github.com/riscv
  - PRJ=riscv-pk                                       SRC=https://github.com/riscv
  - PRJ=riscv-poky                                     SRC=https://github.com/riscv
  - PRJ=riscv-qemu                                     SRC=https://github.com/riscv
  - PRJ=riscv-strace                                   SRC=https://github.com/riscv
  - PRJ=riscv-test-env                                 SRC=https://github.com/riscv
  - PRJ=riscv-tests                                    SRC=https://github.com/riscv
  - PRJ=riscv-tools                                    SRC=https://github.com/riscv
  - PRJ=riscv-weekly                                   SRC=https://github.com/riscv
  - PRJ=riscv-wiki                                     SRC=https://github.com/riscv
  - PRJ=bar-crawl-web                                  SRC=https://github.com/ucb-bar
  - PRJ=barstools                                      SRC=https://github.com/ucb-bar
  - PRJ=berkeley-hardfloat                             SRC=https://github.com/ucb-bar
  - PRJ=berkeley-softfloat-3                           SRC=https://github.com/ucb-bar
  - PRJ=berkeley-testfloat-3                           SRC=https://github.com/ucb-bar
  - PRJ=bits                                           SRC=https://github.com/ucb-bar
  - PRJ=ccbench                                        SRC=https://github.com/ucb-bar
  - PRJ=chipper                                        SRC=https://github.com/ucb-bar
  - PRJ=chipper-tutorial                               SRC=https://github.com/ucb-bar
  - PRJ=chisel                                         SRC=https://github.com/ucb-bar
  - PRJ=chisel-library-template                        SRC=https://github.com/ucb-bar
  - PRJ=chisel-sift                                    SRC=https://github.com/ucb-bar
  - PRJ=chisel-template                                SRC=https://github.com/ucb-bar
  - PRJ=chisel-torture                                 SRC=https://github.com/ucb-bar
  - PRJ=chisel-tutorial                                SRC=https://github.com/ucb-bar
  - PRJ=chisel3-wiki                                   SRC=https://github.com/ucb-bar
  - PRJ=context-dependent-environments                 SRC=https://github.com/ucb-bar
  - PRJ=dsptools                                       SRC=https://github.com/ucb-bar
  - PRJ=fpga-images-zc706                              SRC=https://github.com/ucb-bar
  - PRJ=fpga-images-zedboard                           SRC=https://github.com/ucb-bar
  - PRJ=fpga-images-zybo                               SRC=https://github.com/ucb-bar
  - PRJ=fpga-spartan6                                  SRC=https://github.com/ucb-bar
  - PRJ=fpga-zynq                                      SRC=https://github.com/ucb-bar
  - PRJ=hurricane-serial                               SRC=https://github.com/ucb-bar
  - PRJ=opencl-kernels                                 SRC=https://github.com/ucb-bar
  - PRJ=OpenSoCFabric                                  SRC=https://github.com/ucb-bar
  - PRJ=pfpmp                                          SRC=https://github.com/ucb-bar
  - PRJ=plsi                                           SRC=https://github.com/ucb-bar
  - PRJ=project-template                               SRC=https://github.com/ucb-bar
  - PRJ=pwm-chisel-example                             SRC=https://github.com/ucb-bar
  - PRJ=riscv-benchmarks                               SRC=https://github.com/ucb-bar
  - PRJ=riscv-boom                                     SRC=https://github.com/ucb-bar
  - PRJ=riscv-mini                                     SRC=https://github.com/ucb-bar
  - PRJ=riscv-qemu-deprecated                          SRC=https://github.com/ucb-bar
  - PRJ=riscv-sodor                                    SRC=https://github.com/ucb-bar
  - PRJ=riscv-torture                                  SRC=https://github.com/ucb-bar
  - PRJ=rocc-template                                  SRC=https://github.com/ucb-bar
  - PRJ=sbt-extras                                     SRC=https://github.com/ucb-bar
  - PRJ=testchipip                                     SRC=https://github.com/ucb-bar
  - PRJ=ucb-bar.github.io                              SRC=https://github.com/ucb-bar
  - PRJ=vcd2step                                       SRC=https://github.com/ucb-bar
  - PRJ=vscale                                         SRC=https://github.com/ucb-bar
  - PRJ=www-bar                                        SRC=https://github.com/ucb-bar
  - PRJ=zscale                                         SRC=https://github.com/ucb-bar
  - PRJ=Adafruit_BluefruitLE_nRF51                     SRC=https://github.com/sifive
  - PRJ=Adafruit_ILI9341                               SRC=https://github.com/sifive
  - PRJ=aptly-formula                                  SRC=https://github.com/sifive
  - PRJ=bind-formula                                   SRC=https://github.com/sifive
  - PRJ=buildroot                                      SRC=https://github.com/sifive
  - PRJ=cinco                                          SRC=https://github.com/sifive
  - PRJ=debug-mechanism-comparison                     SRC=https://github.com/sifive
  - PRJ=freedom                                        SRC=https://github.com/sifive
  - PRJ=freedom-e-sdk                                  SRC=https://github.com/sifive
  - PRJ=freedom-u-sdk                                  SRC=https://github.com/sifive
  - PRJ=jtag_vpi                                       SRC=https://github.com/sifive
  - PRJ=mysql-formula                                  SRC=https://github.com/sifive
  - PRJ=riscv-binutils-gdb                             SRC=https://github.com/sifive
  - PRJ=riscv-gnu-toolchain                            SRC=https://github.com/sifive
  - PRJ=riscv-linux                                    SRC=https://github.com/sifive
  - PRJ=riscv-pk                                       SRC=https://github.com/sifive
  - PRJ=riscv-tests                                    SRC=https://github.com/sifive
  - PRJ=sifive-blocks                                  SRC=https://github.com/sifive
  - PRJ=slurm-formula                                  SRC=https://github.com/sifive
  - PRJ=chisel                                         SRC=https://github.com/lowrisc
  - PRJ=chisel-components                              SRC=https://github.com/lowrisc
  - PRJ=context-dependent-environments                 SRC=https://github.com/lowrisc
  - PRJ=flexpret                                       SRC=https://github.com/lowrisc
  - PRJ=fpga-zynq                                      SRC=https://github.com/lowrisc
  - PRJ=glip                                           SRC=https://github.com/lowrisc
  - PRJ=greth-library                                  SRC=https://github.com/lowrisc
  - PRJ=hjson_to_gantt                                 SRC=https://github.com/lowrisc
  - PRJ=lowrisc-bbl                                    SRC=https://github.com/lowrisc
  - PRJ=lowrisc-chip                                   SRC=https://github.com/lowrisc
  - PRJ=lowrisc-doc                                    SRC=https://github.com/lowrisc
  - PRJ=lowrisc-docker                                 SRC=https://github.com/lowrisc
  - PRJ=lowrisc-fpga                                   SRC=https://github.com/lowrisc
  - PRJ=lowrisc-images-zedboard                        SRC=https://github.com/lowrisc
  - PRJ=lowrisc-kc705                                  SRC=https://github.com/lowrisc
  - PRJ=lowrisc-kc705-images                           SRC=https://github.com/lowrisc
  - PRJ=lowrisc-nexys4                                 SRC=https://github.com/lowrisc
  - PRJ=lowrisc-nexys4-video                           SRC=https://github.com/lowrisc
  - PRJ=lowrisc-site                                   SRC=https://github.com/lowrisc
  - PRJ=lowrisc-tag-tests                              SRC=https://github.com/lowrisc
  - PRJ=lowrisc-tests                                  SRC=https://github.com/lowrisc
  - PRJ=lowrisc.github.io                              SRC=https://github.com/lowrisc
  - PRJ=minion_subsystem                               SRC=https://github.com/lowrisc
  - PRJ=riscv-binutils-gdb                             SRC=https://github.com/lowrisc
  - PRJ=riscv-calling-conv-model                       SRC=https://github.com/lowrisc
  - PRJ=riscv-dejagnu                                  SRC=https://github.com/lowrisc
  - PRJ=riscv-fesvr                                    SRC=https://github.com/lowrisc
  - PRJ=riscv-gcc                                      SRC=https://github.com/lowrisc
  - PRJ=riscv-gcc-tagged-memory-v0.1                   SRC=https://github.com/lowrisc
  - PRJ=riscv-glibc                                    SRC=https://github.com/lowrisc
  - PRJ=riscv-gnu-toolchain                            SRC=https://github.com/lowrisc
  - PRJ=riscv-isa-sim                                  SRC=https://github.com/lowrisc
  - PRJ=riscv-linux                                    SRC=https://github.com/lowrisc
  - PRJ=riscv-llvm                                     SRC=https://github.com/lowrisc
  - PRJ=riscv-newlib                                   SRC=https://github.com/lowrisc
  - PRJ=riscv-opcodes                                  SRC=https://github.com/lowrisc
  - PRJ=riscv-pk                                       SRC=https://github.com/lowrisc
  - PRJ=riscv-test-env                                 SRC=https://github.com/lowrisc
  - PRJ=riscv-tests                                    SRC=https://github.com/lowrisc
  - PRJ=riscv-tools                                    SRC=https://github.com/lowrisc
  - PRJ=rocket                                         SRC=https://github.com/lowrisc
  - PRJ=socip                                          SRC=https://github.com/lowrisc
  - PRJ=uncore                                         SRC=https://github.com/lowrisc
  - PRJ=zscale                                         SRC=https://github.com/lowrisc
  global:
  - secure: TEcQb4qDLq2eVEwuZ9SDzOAyFNXErv5UrdEAC8+1d/h0eXAc+ubY+RGx0aKblpYpOLQLzMmwTJMEcxjhA6VflXNznpK2fnDpL1Rl3t0szI8toDu/qe7p8Ejyqsrq1yYmPKPFEhvyaTul0TQqdfGW4c26TPTtTGhf3vYJy56aQxF3HK6YS1YNnR1rD7ujwBtQqaKt4vFAj9KNU5X9jOaqxpvjTerRAJ9Sk8xgDdaHblalWZvInV85lyzDrm44DXPc5/HaxgzkTcBvKTlF1zcOVVTwPnrJjY+ucrkfvkQMdP+yk7PPbfGhCsx3B1Mpw95AiqvNk/eXukzVY63oKUTQ14UgRaC4a7OqUm7oTlAXESvR9msmsE1t3236yxUSBkmzEYZOhqj+qDBNxmPr/ajS/DYxBSNgedAquWlhs4vOeZB3yxo5GZ8/HJJ/BAv1g6iW9OR1GRkLU1lmZdRx0WN5mXu5RFYbiYsMUoyU18+eATVSZCpkCIIv0hA5kY1cCNsC95HgU02SSgkNkCfaIO4anLKt7W495KsPH6dnylf6kAByVGWgdsZsLl6QTUJBODCpN3kDGxxfl1TZ8X5acnemNYvvavh32WH1fvylQOcCSihSjMjMHe/pipX8x/55IDs6BoVOpOuuIw6DzSPh21oAb6YsYjJOIXNzYL89V+C3gAc=
script:
- export WORK=$HOME/.sync
- "./sync.sh"
cache:
  directories:
  - "$HOME/.sync"
